name: Linters

on:
  push:
    # Run on pushes to specific branches
    branches:
      - master
      - next
      - beta
      - alpha
    # Do not run on tags
    tags-ignore:
      - "*"
  pull_request:
    # Run on to branches with an open PR
    branches:
      - "*"

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run linters
        run: yarn lint
      # - name: Run tests # TODO: Run tests after add env variable to secrets
      #   with:
      #     run: |
      #       yarn tsc
      #       yarn test:unit